apiVersion: v2
name: otel-collector
version: 0.1.0
description: OpenTelemetry Collector - Reusable base chart for Mirador Signals Pipeline
type: application
home: https://opentelemetry.io/
sources:
  - https://github.com/open-telemetry/opentelemetry-collector
  - https://github.com/open-telemetry/opentelemetry-collector-contrib
maintainers:
  - name: dmitryax
  - name: jaronoff97
  - name: TylerHelmuth
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
appVersion: 0.138.0
